<script src="../assets/extensions/perfect-scrollbar/perfect-scrollbar.min.js"></script>
<script src="https://cdn.datatables.net/v/bs5/dt-1.12.1/datatables.min.js"></script>
<script src="../assets/js/pages/dashboard.js"></script>
<script src="../assets/js/bootstrap.js"></script>
<script src="../assets/js/app.js"></script>
<script src="../assets/extensions/jquery/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/choices.js/2.8.3/choices.js"></script>
<script src="assets/js/pages/form-element-select.js"></script>
<!-- <script src="/dist/assets/js/bootstrap.min.js"></script>-->
<!-- <script src="/assets/js/main.js"></script> -->
